### ISSUE TITLE
#9 Divs

### ISSUE THREAD

**Issue by ReneKrewinkel** [RobinHaerkens/educom-html#9]
<p>Volg het onderdeel "Divs" en maak de opdracht.</p>
<p><a href="https://e-learning.educom.nu/essentials/HTML/divs">https://e-learning.educom.nu/essentials/HTML/divs</a></p>

**Comment by RobinHaerkens** [comment]
De vraag waarom dit gebeurt; als je beide afbeeldingen in een div tag plaatst, is waarschijnlijk omdat je een blok maakt en hij dus beide afbeeldingen naast elkaar in het zelfde blok zet.
